### PR TITLE
Docker image generation

### PR DESCRIPTION
**Pull request by mcg1969**
Rebased version of #17

### CODE REVIEW

**Comment by mcg1969** [comment]
@AlbertDeFusco so I've rebased this a couple of times and played with it—I definitely like it. My one concern is the `--use-anaconda-cloud` option and the motivation/consequences. In particular, if you _don't_ use it, then you are assuming a particular channel structure on the cluster. What I'd rather do, if we can figure out a way to do it, is to retrieve the conda configuration settings from the cluster and use those. Do you think that's doable?

**Comment by mcg1969** [comment]
OK, that's not my only concern—I would also like to get the Docker output delivered to stderr in real time.

**Comment by AlbertDeFusco** [comment]
Ok. I can work on those two. What conda config would you want? The `.condarc` or the ConfigMap?

**Comment by mcg1969** [comment]
I think we have to pull from ConfigMap, because now we're using `build_condarc.py` and environment variables to _build_ the `.condarc` that lives in a session.

**Comment by mcg1969** [comment]
@AlbertDeFusco I'm guilty of letting the perfect be the enemy of the good here. I want to get this merged—and I think that as long as we can customize both the Dockerfile (done) and the .condarc (not done) we're fine.

**Comment by AlbertDeFusco** [comment]
I've done as we talked

* remove docker-py
* custom condarc

**Comment by mcg1969** [comment]
Thanks! Corrected the merge commit and I think we're good. Fingers crossed

**Comment by mcg1969** [comment]
So cool. Thanks Albert!

**Comment by AlbertDeFusco** [comment]
hurray!!

**Comment by mcg1969** [comment]
Hmm, I'm having some issues with R shiny. Might have to do some adjusting. But I'll figure it out. At worst it's a Dockerfile modification

**Pull request merged**
