### PR TITLE
Proposal for PromQL deployment

### PR DESCRIPTION
**Pull request by jlstevens**
This PR is very much WIP right now but it puts forward the idea that along with the `k8s` deployment, there could be another deployment (`promql`) that you could upload with `ae5-tools`. This deployment would make prometheus information in the AE5 cluster available to `ae5-tools` itself or anything else with the right permissions (e.g [lumen](https://github.com/holoviz/lumen)).

This deployment would need many of the same instructions (currently under [BETA: Kubernetes information support](https://github.com/Anaconda-Platform/ae5-tools#beta-kubernetes-information-support)) to be followed as for the k8s deployment (as it also needs a Kubernetes API bearer token) but then you could then do something like the following to create a second deployment exposing Prometheus information:

```bash
ae5 deployment start promql --command promql --endpoint k8s --private --wait
```

This deployment discovers where Prometheus is running on the AE5 master node, passes PromQL queries to it and forwards the responses back. The information exposed by Prometheus could then be exposed by the `ae5-tools` commandline giving admins a nice way to monitor the cluster over time.

This PR still needs a lot of refactoring, testing and improvements before it could be merged.

## TODO

* [x] Use the same `asyncio` and `aiohttp` approach as the `k8s` deployment.
* [ ] Consider if the ssh access approach applies here (probably) and implement it
* [x] See if `AE5K8STransformer` which handles the bearer token can be shared between the k8s and this promql deployment.
* [ ] Update the docs and instructions
* [ ] Think about how ae5-tools might offer useful information obtained from prometheus back to users.

### CODE REVIEW

**Comment by philippjfr** [comment]
@mcg1969 Any opinions on how to organize this? Some thoughts:

1. No guarantee this is the last service we expose via a REST API so should there be a `rest` or `service` subpackage that both k8s and promql go in?
2. Should there be `AE5BaseServer`, `AE5BaseTransformer` and `AE5BaseClient` base classes?

**Comment by mcg1969** [comment]
It's not clear to me why we should have multiple deployments. Rather, I'd prefer to see us implement an API layer that combines these sources of information into one, so that a single deployment does the job. So my vote is #1. I don't care what the default domain name is. I mean, k8s seems safe enough, but I'm open to alternatives

**Comment by jlstevens** [comment]
Merging into a single deployment would certainly simplify things. That said, I seem to remember that prometheus is configured quite differently (or at least exposed differently) in earlier versions of AE5 (unlike the k8s deployment which is unaffected). If we merge the deployments, we might need to disable the promql functionality for earlier AE5 versions (which might be a decision we are happy to make).

**Comment by mcg1969** [comment]
Certainly. Let's assume a minimum AE version for promql￼

**Comment by philippjfr** [comment]
Strong +1 on merging the two. Will try to finish that tomorrow.

**Comment by philippjfr** [comment]
Okay I've now merged the promql server into the `AE5K8SHandler` and moved the AE5PromQLTransformer into the `k8s/transformer.py` module. Much happier with this. Probably should have done this in a separate PR but I couldn't help but apply linting as well, which uncovered a few small issues (with undefined variables), if you could tell me what `stream` should refer to here I'll fix that as well:

https://github.com/Anaconda-Platform/ae5-tools/blob/5d552e16faaf71b679fcd6f90b77d628c1842b52/ae5_tools/k8s/client.py#L31  

>Certainly. Let's assume a minimum AE version for promql￼

Not sure how to enforce this, currently I try to fetch the prometheus IP and if that fails I have the `/promql/__status__` and `/promql/query_range` endpoints return `HTTPMethodNotAllowed(reason="AE5 instance does not expose PromQL service.")`. Will have to see if that behaves as expected on earlier versions.

**Comment by jlstevens** [comment]
This PR has now been rebased and I've tested the promql support on the pyviz cluster and it is working.

Unfortunately, there is now a mix of `requests` and `aiohttp`. I suggest we merge, @philippjfr has offered to submit a PR to remove requests at which point I'm happy to test the promql support again.

**Comment by philippjfr** [comment]
Actually looking at this I'm a bit confused now. The entire `AESession` API uses `requests` and exposes synchronous methods for querying information. This means that if I convert the `AE5K8SClient` to be asynchronous then the `AEUserSession` methods would have to be converted to be asynchronous as well leading to a lot of inconsistency.

**Comment by philippjfr** [comment]
I do think it would be nice to offer asynchronous version of the AEUserSession API though but that's part of a much bigger effort.

**Comment by jlstevens** [comment]
@philippjfr Happy to see this merged then?

**Comment by philippjfr** [comment]
Yes, well overdue 🙂

**Pull request merged**
